name: Run test and coverage

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
      types: [opened, reopened, synchronize]
    release:
      types: [published]
    workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: mamba-org/setup-micromamba@v1
      - name: Setup Mantid
        run: |
          $MAMBA_EXE create -n cfutils -c mantid mantidworkbench
      - name: Test
        run: |
          eval "$($MAMBA_EXE shell activate cfutils)"
          python -m unittest tests/examples_tests.py
      #- name: Setup tmate
      #  if: ${{ failure() }}
      #  uses: mxschmitt/action-tmate@v3
